### ISSUE TITLE
[BUG] Using orbital miner, it will randomly crash the game with "java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!"

### ISSUE THREAD

**Issue by crzyblue** [dercodeKoenig/AdvancedRocketry#12]
## Version of Advanced Rocketry
>AdvancedRocketry-1.12.2-2.0.5-23-05-06-06-2024

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>LibVulpes-1.12.2-0.4.2-25-universal

## Version of Minecraft
>1.12.2

## Does this occur without other mods installed
- [x] N/A
>If Y, what is the MINIMUM set of mods required.

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
>https://mclo.gs/D2EtNIC

> If it's an issue involving lag, please submit a visualVM sampler snapshot.  Mods like lag goggles often do not provide the kind of information needed to debug lag.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem
>Using the orbital miner in the space station, it randomly crashes the game with the provided error log. We have our overworld planet (Nova, dim 100) chunk loaded, so it should be loaded at all times.

**Comment by dercodeKoenig** [comment]
Do you use void mining or planet mining? in the config you can set the laser to not actually break the blocks on the planet below. This mode is "void mining".
Planet mining is where the laser actually breaks blocks below. 

Planet mining bugs are not fixed currently but will be later when I have more time.
For now, use void mining mode. Void mining is already fixed and should not crash the game.

I know about the planet mining bugs

**Comment by crzyblue** [comment]
# If true the orbital laser will actually mine blocks on the planet below (currently not working)
    B:laserDrillPlanet=false

**Comment by dercodeKoenig** [comment]
the planet mining will be fixed in the next release
