### ISSUE TITLE
[Request] Rework how large moons appear in the sky

### ISSUE THREAD

**Issue by xkforce** [dercodeKoenig/AdvancedRocketry#13]
The size of moons in the sky should be either independent of the moon's distance from its parent planet (relative to the vanilla moon) or be based on diameter (which cannot be specified) and orbital distance again both relative to the vanilla moon.

**Comment by dercodeKoenig** [comment]
the size of a planet/moon is based on its gravitational multiplier as the size is responsible for gravitation. For rendering, the size is based on its gravitational multiplier and the distance

**Comment by dercodeKoenig** [comment]
I will consider this issue closed now. you can reopen a new issue if your problem was not fixed
