### ISSUE TITLE
[BUG] Building a centrifuge crashes and permanently corrupts the world.

### ISSUE THREAD

**Issue by MrEyeballs29** [dercodeKoenig/AdvancedRocketry#20]
## Version of Advanced Rocketry
2.0.11-1 

## Have you verified this is an issue in the latest unstable build
Yes

## Version of LibVulpes
0.4.2.-25

## Does this occur without other mods installed
Only this mod.

## Crash report or log or visualVM (if applicable)
https://pastebin.com/yYdY2fYu

## Description of the problem
When I build the centrifuge the game crashes. Also the world becomes permanently corrupted.

Steps to reproduce:
1.  Build a centrifuge in survival.
2.  Activate multiblock.
3.  Game Crashes

Expected Behavior: The multiblock is formed.

**Comment by dercodeKoenig** [comment]
The new Advanced Rocketry requires the new LibVulpes build. Libvulpes had many bugs that have been fixed in the new Libvulpes.
Due to the stupidity of shitforge, I had to rename the new libvulpes to ARLib

**Comment by dercodeKoenig** [comment]
the lates libvulpes is 0.4.3

**Comment by MrEyeballs29** [comment]
Oh I get it now. The old mod was breaking.
