### ISSUE TITLE
[Request] Complete `Energy Hatch` capacity multiplier

### ISSUE THREAD

**Issue by Krutoy242** [dercodeKoenig/AdvancedRocketry#33]
Considering [this commit](https://github.com/dercodeKoenig/libVulpes-fork2/commit/58111e0b67c16fb142477689edd75ff2827156c2), only `getMaxEnergy` is patched. This means, `getMaxDrainRate` is left unpatched, thus with huge multipliers, transfer rate will be impossible slow, making machines unefficient.

Please make it so multiplier multiply transfer rate too.

**Comment by dercodeKoenig** [comment]
https://github.com/dercodeKoenig/libVulpes-fork2/commit/be9238f2e64ce81273f731abef50db0322ee0771
